@Prova30 = http://localhost:5288

### Cadastrar Usuario
POST {{Prova30}}/api/usuario/cadastrar
Content-Type: application/json

{
  "email": "Pedro Brocha",
  "senha": "12",
  "role": 1
}

### Listar Usuario
GET {{Prova30}}/api/usuario/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQnJvY2hhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDY0OTUzNTd9.TdeQvTnNgeJac7MMfhvWBV676GZ-ADqhu66Ku66FmVQ

### Login Usuario
POST {{Prova30}}/api/usuario/login
Content-Type: application/json

{
  "email": "Pedro Brocha",
  "senha": "12"
}

### Cadastrar Evento
POST {{Prova30}}/api/eventos/cadastrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQnJvY2hhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDY0OTUzNTd9.TdeQvTnNgeJac7MMfhvWBV676GZ-ADqhu66Ku66FmVQ
Content-Type: application/json
    
{
    "nome": "Suruba do Gabriel",
    "data": "2025-06-03T12:00:00",
    "local": "Casa do Pedro",
    "usuarioId": 6
}

### Listar Evento
GET {{Prova30}}/api/eventos/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQnJvY2hhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDY0OTUzNTd9.TdeQvTnNgeJac7MMfhvWBV676GZ-ADqhu66Ku66FmVQ

### Eventos por Usuario
GET {{Prova30}}/api/eventos/eventoUsuario/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQnJvY2hhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDY0OTUzNTd9.TdeQvTnNgeJac7MMfhvWBV676GZ-ADqhu66Ku66FmVQ