@Prova30 = http://localhost:5288

### Cadastrar Usuario
POST {{Prova30}}/api/usuario/cadastrar
Content-Type: application/json

{
  "email": "lukinhas",
  "senha": "12345"
}

### Listar Usuario
GET {{Prova30}}/api/usuario/listar

### Login Usuario
POST {{Prova30}}/api/usuario/login
Content-Type: application/json

{
  "email": "lukinhas",
  "senha": "12345"
}

### Cadastrar Evento
POST {{Prova30}}/api/eventos/cadastrar
Content-Type: application/json
    
{
    "nome": "Balacobaco",
    "data": "2025-06-03T12:00:00",
    "local": "Casa Amarela",
    "usuarioId": 2
}

### Listar Evento
GET {{Prova30}}/api/eventos/listar

### Eventos por Usuario
GET {{Prova30}}/api/eventos/eventoUsuario/2