@Prova30 = http://localhost:5288

### Cadastrar Usuario
POST {{Prova30}}/api/usuario/cadastrar
Content-Type: application/json

{
  "email": "lucasss",
  "senha": "12345",
  "role": 1
}

### Listar Usuario
GET {{Prova30}}/api/usuario/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXNzcyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwiZXhwIjoxNzQ2NDk0MzYwfQ.krJbGdE77K0OBz_Sj7UJ6vPF-C-6BVM9BZsEpYTKrqs

### Login Usuario
POST {{Prova30}}/api/usuario/login
Content-Type: application/json

{
  "email": "lucasss",
  "senha": "12345"
}

### Cadastrar Evento
POST {{Prova30}}/api/eventos/cadastrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXNzcyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwiZXhwIjoxNzQ2NDk0NjQ1fQ.URR_ST2JimLhqyUFFJgTWH2C-iZsj7xkmv4tLQplf4c
Content-Type: application/json
    
{
    "nome": "Festinha muito legal",
    "data": "2025-06-03T12:00:00",
    "local": "Casinha",
    "usuarioId": 1
}

### Listar Evento
GET {{Prova30}}/api/eventos/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXNzcyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwiZXhwIjoxNzQ2NDk0ODExfQ.hRF1YRB0D6yu5zIeKJKfyQA_EHp43YT2QmhJTgmpEPY

### Eventos por Usuario
GET {{Prova30}}/api/eventos/eventoUsuario/2